schema = 3

[mod]
  [mod."github.com/btcsuite/btcd"]
    version = "v0.23.0"
    hash = "sha256-cDMCqIriUzp/thVg46V0+CDKRQAGZvaIjmdYbYKM1aM="
  [mod."github.com/btcsuite/btcd/btcec/v2"]
    version = "v2.1.3"
    hash = "sha256-qAahjPElRpX4L3NpyOOVZi5NOhqAQ+trGW26bXm+emo="
  [mod."github.com/btcsuite/btcd/btcutil"]
    version = "v1.1.3"
    hash = "sha256-6Y9sP1yvPBO8PhqmFVVXNV7dxsXlERDAB+TPTEfW3kI="
  [mod."github.com/btcsuite/btcd/chaincfg/chainhash"]
    version = "v1.0.1"
    hash = "sha256-vix0j/KGNvoKjhlKgVeSLY6un2FHeIEoZWMC4z3yvZ4="
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.0.1"
    hash = "sha256-JBVRp40dDj0puapoQloV13H6TMjgJiypzYojcDRE2jI="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.4.0"
    hash = "sha256-LwOrfDN5fx/R2lgaD90RIu2NxcJDpyqYEURLc9Kgxgw="
  [mod."github.com/skip2/go-qrcode"]
    version = "v0.0.0-20200617195104-da1b6568686e"
    hash = "sha256-ST9t4/b7WFXUb8wra4ZYVDNZJGrEykw8dkWhLrxp8F0="
  [mod."github.com/srwiley/rasterx"]
    version = "v0.0.0-20220730225603-2ab79fcdd4ef"
    hash = "sha256-/XmSE/J+f6FLWXGvljh6uBK71uoCAK3h82XQEQ1Ki68="
  [mod."github.com/tarm/serial"]
    version = "v0.0.0-20180830185346-98f6abe2eb07"
    hash = "sha256-646ngos1o2K+T+wxZpfuaQKrWqWZuta5iqMPJ3aURPo="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."golang.org/x/crypto"]
    version = "v0.7.0"
    hash = "sha256-Yc4casCQyfOgIr48FV+NI9qhanhBuYnkph5iI7rDyZE="
  [mod."golang.org/x/image"]
    version = "v0.6.0"
    hash = "sha256-fZc2Jfh6EqsjmMBUMaGHn8+bSMetuZ7K4AxU8BRXt94="
  [mod."golang.org/x/sys"]
    version = "v0.6.0"
    hash = "sha256-zAgxiTuL24sGhbXrna9R1UYqLQh46ldztpumOScmduY="
  [mod."golang.org/x/text"]
    version = "v0.8.0"
    hash = "sha256-hgWFnT01DRmywBEXKYEVaOee7i6z8Ydz7zGbjcWwOgI="
  [mod."periph.io/x/conn/v3"]
    version = "v3.7.0"
    hash = "sha256-UL6B0d9K8T3XrSYDrHDeaKAdkUh/Wf+NdhPRriE8Bzw="
  [mod."periph.io/x/host/v3"]
    version = "v3.8.2"
    hash = "sha256-A2WZA2Y4GRXPLuwuSDXXhWkzuKHr/7YsBaBdw3C4QyM="
