name: "Build image"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - uses: DeterminateSystems/magic-nix-cache-action@v1
    - name: Set version to GITHUB_SHA
      if: ${{ github.ref_type != 'tag' }}
      run: echo "version=${{ github.sha }}" >> $GITHUB_ENV
    - name: Set version to GITHUB_REF_NAME
      if: ${{ github.ref_type == 'tag' }}
      run: echo "version=${{ github.ref_name }}" >> $GITHUB_ENV
    - run: nix build -L
    - run: nix run -L .#stamp-release ${{ env.version }}
    - uses: actions/upload-artifact@v3
      with:
        name: seedhammer-${{ env.version }}.img
        path: seedhammer-${{ env.version }}.img
